stiri =("România rămâne în topul țărilor din Uniunea Europeană.")
impartit = len (stiri)
print(impartit / 2)
print(impartit)
majuscule = stiri.upper()
print(majuscule)
eliminare_spati_stanga = stiri.lstrip()
eliminare_spati_dreapta = stiri.rstrip()
print(eliminare_spati_stanga , eliminare_spati_dreapta)
invers = stiri[::-1].upper()
print(invers)
majuscula_primul_cuv = stiri.capitalize()
print(majuscula_primul_cuv)
import string
fara_puncte_de_punctuatie = "".join(ch for ch in stiri if ch not in string.punctuation)
print(fara_puncte_de_punctuatie)